/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.projetointegrador;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author lukev
 */
public class Departamentos extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Departamentos() {
        initComponents();
        
        setTitle("Cadastro Departamentos");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LISTA = new javax.swing.JLabel();
        lista = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        menu = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        save = new javax.swing.JButton();
        func = new javax.swing.JTextField();
        serv = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        RAMO = new javax.swing.JLabel();
        CNPJ = new javax.swing.JLabel();
        NOME = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LISTA.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        LISTA.setForeground(new java.awt.Color(255, 255, 255));
        LISTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LISTA.setText("Departamentos Cadastrados");
        getContentPane().add(LISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 300, -1));

        area.setColumns(20);
        area.setRows(5);
        lista.setViewportView(area);

        getContentPane().add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 280, 220));

        menu.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, 40));

        clean.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        clean.setText("Limpar");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });
        getContentPane().add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, 40));

        save.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        save.setText("Salvar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, 40));

        func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcActionPerformed(evt);
            }
        });
        getContentPane().add(func, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 180, 40));

        serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servActionPerformed(evt);
            }
        });
        getContentPane().add(serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 40));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 320, 40));

        RAMO.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        RAMO.setForeground(new java.awt.Color(255, 255, 255));
        RAMO.setText("Cód. Funcionário:");
        getContentPane().add(RAMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 40));

        CNPJ.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        CNPJ.setForeground(new java.awt.Color(255, 255, 255));
        CNPJ.setText("Cód. Serviço:");
        getContentPane().add(CNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 40));

        NOME.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        NOME.setForeground(new java.awt.Color(255, 255, 255));
        NOME.setText("Nome:");
        getContentPane().add(NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Cadastro - Departamentos.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 330, 90));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Fundo - Início.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servActionPerformed

    private void funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Confirma Salvar?", "Opções", JOptionPane.YES_NO_CANCEL_OPTION);
        boolean invalido = true;
        
        if(valor == 0){
            // Sim
            Dep d = new Dep();
            d.setNome(nome.getText());
            
            try{
                d.setServ(Integer.parseInt(serv.getText()));
                d.setFunc(Integer.parseInt(func.getText()));
                invalido = false;
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Cód. Serviço ou Cód. Funcionário digitado incorretamente!\n" +e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                serv.setText("");
                func.setText("");
            }
            
            if(invalido == false){
                area.setText(d.status());
            }
        }
        else if(valor == 1){
            // Não
        }
        else{
            // Cancela
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling codclientere:
        nome.setText("");
        serv.setText("");
        func.setText("");
    }//GEN-LAST:event_cleanActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new Setores().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Departamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CNPJ;
    private javax.swing.JLabel LISTA;
    private javax.swing.JLabel NOME;
    private javax.swing.JLabel RAMO;
    private javax.swing.JTextArea area;
    private javax.swing.JButton clean;
    private javax.swing.JTextField func;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane lista;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nome;
    private javax.swing.JButton save;
    private javax.swing.JTextField serv;
    // End of variables declaration//GEN-END:variables
}
