/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.projetointegrador;

/**
 *
 * @author lukev
 */
public class Financeiro extends javax.swing.JFrame {

    /**
     * Creates new form Financeiro
     */
    public Financeiro() {
        initComponents();
        
        setTitle("Financeiro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sal = new javax.swing.JButton();
        compras = new javax.swing.JButton();
        contas = new javax.swing.JButton();
        vendas = new javax.swing.JButton();
        out = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sal.setBackground(new java.awt.Color(255, 255, 255));
        sal.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        sal.setText("Salário");
        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });
        getContentPane().add(sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 190, 60));

        compras.setBackground(new java.awt.Color(255, 255, 255));
        compras.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        compras.setText("Compras");
        compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasActionPerformed(evt);
            }
        });
        getContentPane().add(compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 190, 60));

        contas.setBackground(new java.awt.Color(255, 255, 255));
        contas.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        contas.setText("Contas");
        contas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contasActionPerformed(evt);
            }
        });
        getContentPane().add(contas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 190, 60));

        vendas.setBackground(new java.awt.Color(255, 255, 255));
        vendas.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        vendas.setText("Vendas");
        vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasActionPerformed(evt);
            }
        });
        getContentPane().add(vendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 190, 60));

        out.setBackground(new java.awt.Color(255, 255, 255));
        out.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        out.setText("Voltar");
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        getContentPane().add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 100, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Logo - Menu Financeiro.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 440, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Fundo - Início.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
        dispose();
        new Salario().setVisible(true);
    }//GEN-LAST:event_salActionPerformed

    private void comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasActionPerformed
        // TODO add your handling code here:
        dispose();
        new Compras().setVisible(true);
    }//GEN-LAST:event_comprasActionPerformed

    private void contasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contasActionPerformed
        // TODO add your handling code here:
        dispose();
        new Contas().setVisible(true);
    }//GEN-LAST:event_contasActionPerformed

    private void vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasActionPerformed
        // TODO add your handling code here:
        dispose();
        new Vendas().setVisible(true);
    }//GEN-LAST:event_vendasActionPerformed

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Financeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Financeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compras;
    private javax.swing.JButton contas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton out;
    private javax.swing.JButton sal;
    private javax.swing.JButton vendas;
    // End of variables declaration//GEN-END:variables
}
