/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.projetointegrador;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author lukev
 */
public class Fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Fornecedor() {
        initComponents();
        
        setTitle("Cadastro Fornecedores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LISTA = new javax.swing.JLabel();
        lista = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        menu = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        save = new javax.swing.JButton();
        endereco = new javax.swing.JTextField();
        cnpj = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        END = new javax.swing.JLabel();
        CNPJ = new javax.swing.JLabel();
        NOME = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LISTA.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        LISTA.setForeground(new java.awt.Color(255, 255, 255));
        LISTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LISTA.setText("Fornecedores Cadastrados");
        getContentPane().add(LISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 290, -1));

        area.setColumns(20);
        area.setRows(5);
        lista.setViewportView(area);

        getContentPane().add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 290, 220));

        menu.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, 40));

        clean.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        clean.setText("Limpar");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });
        getContentPane().add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, 40));

        save.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        save.setText("Salvar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, 40));

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 280, 30));

        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });
        getContentPane().add(cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 320, 30));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 320, 30));

        END.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        END.setForeground(new java.awt.Color(255, 255, 255));
        END.setText("Endereço:");
        getContentPane().add(END, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 30));

        CNPJ.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        CNPJ.setForeground(new java.awt.Color(255, 255, 255));
        CNPJ.setText("CNPJ:");
        getContentPane().add(CNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 30));

        NOME.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        NOME.setForeground(new java.awt.Color(255, 255, 255));
        NOME.setText("Nome:");
        getContentPane().add(NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Cadastro - Fornecedores.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 330, 90));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Fundo - Início.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Confirma Salvar?", "Opções", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(valor == 0){
            // Sim
            Fornec forn = new Fornec();
            forn.setNome(nome.getText());
            forn.setCnpj(cnpj.getText());
            forn.setEndereco(endereco.getText());
            
            area.setText(forn.status());
        }
        else if(valor == 1){
            // Não
        }
        else{
            // Cancela
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
        nome.setText("");
        cnpj.setText("");
        endereco.setText("");
    }//GEN-LAST:event_cleanActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        new Stakeholders().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CNPJ;
    private javax.swing.JLabel END;
    private javax.swing.JLabel LISTA;
    private javax.swing.JLabel NOME;
    private javax.swing.JTextArea area;
    private javax.swing.JButton clean;
    private javax.swing.JTextField cnpj;
    private javax.swing.JTextField endereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane lista;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nome;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
