/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.projetointegrador;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author lukev
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        setTitle("Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setores = new javax.swing.JButton();
        financeiro = new javax.swing.JButton();
        stakeholders = new javax.swing.JButton();
        out = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setores.setBackground(new java.awt.Color(255, 255, 255));
        setores.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        setores.setText("Setores");
        setores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setoresActionPerformed(evt);
            }
        });
        getContentPane().add(setores, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 180, 70));

        financeiro.setBackground(new java.awt.Color(255, 255, 255));
        financeiro.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        financeiro.setText("Financeiro");
        financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeiroActionPerformed(evt);
            }
        });
        getContentPane().add(financeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 180, 70));

        stakeholders.setBackground(new java.awt.Color(255, 255, 255));
        stakeholders.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        stakeholders.setText("Stakeholders");
        stakeholders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stakeholdersActionPerformed(evt);
            }
        });
        getContentPane().add(stakeholders, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, 70));

        out.setBackground(new java.awt.Color(255, 255, 255));
        out.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        out.setText("Sair");
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        getContentPane().add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Logo - Menu Principal.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 430, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\LIP\\Projeto Integrador\\Fundo - Início.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_outActionPerformed

    private void financeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeiroActionPerformed
        // TODO add your handling code here:
        dispose();
        new Financeiro().setVisible(true);
    }//GEN-LAST:event_financeiroActionPerformed

    private void stakeholdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stakeholdersActionPerformed
        // TODO add your handling code here:
        dispose();
        new Stakeholders().setVisible(true);
    }//GEN-LAST:event_stakeholdersActionPerformed

    private void setoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setoresActionPerformed
        // TODO add your handling code here:
        dispose();
        new Setores().setVisible(true);
    }//GEN-LAST:event_setoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton financeiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton out;
    private javax.swing.JButton setores;
    private javax.swing.JButton stakeholders;
    // End of variables declaration//GEN-END:variables
}
